#!/usr/bin/env bash
# exit on error
set -o errexit

# install node server deps
npm clean-install --production

# navigate to client dir, and install frontend deps
cd client
npm clean-install --production
npm run build
cd ../

echo Finished build